// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by: packages/frontend/apps/electron/scripts/generate-types.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
export const handlersMeta = {
    "helper": {
        "helper": [
            "test"
        ]
    },
    "main": {
        "appState": [
            "handleGetState",
            "handleUpdateState",
            "handleResetState",
            "handleFlushState"
        ],
        "ui": [
            "showMainWindow",
            "handleThemeChange",
            "isFullScreen",
            "isMaximized",
            "handleMinimizeApp",
            "handleHideApp",
            "handleMaximizeApp"
        ]
    }
};
export const eventsMeta = {
    "main": {
        "appState": [
            "state"
        ],
        "ui": [
            "maximized",
            "fullScreen"
        ]
    }
};
//# sourceMappingURL=ipc-meta.gen.js.map